//! RFC 8621 (JMAP for Mail) coroutines.

#[path = "email-changes.rs"]
pub mod email_changes;
#[path = "email-copy.rs"]
pub mod email_copy;
#[path = "email-get.rs"]
pub mod email_get;
#[path = "email-import.rs"]
pub mod email_import;
#[path = "email-parse.rs"]
pub mod email_parse;
#[path = "email-query.rs"]
pub mod email_query;
#[path = "email-set.rs"]
pub mod email_set;
#[path = "email-submission-cancel.rs"]
pub mod email_submission_cancel;
#[path = "email-submission-get.rs"]
pub mod email_submission_get;
#[path = "email-submission-query.rs"]
pub mod email_submission_query;
#[path = "email-submission-set.rs"]
pub mod email_submission_set;
#[path = "identity-get.rs"]
pub mod identity_get;
#[path = "identity-set.rs"]
pub mod identity_set;
#[path = "mailbox-changes.rs"]
pub mod mailbox_changes;
#[path = "mailbox-get.rs"]
pub mod mailbox_get;
#[path = "mailbox-query.rs"]
pub mod mailbox_query;
#[path = "mailbox-set.rs"]
pub mod mailbox_set;
#[path = "thread-changes.rs"]
pub mod thread_changes;
#[path = "thread-get.rs"]
pub mod thread_get;
#[path = "vacation-response-get.rs"]
pub mod vacation_response_get;
#[path = "vacation-response-set.rs"]
pub mod vacation_response_set;
